### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by raju-jeelaga** [ahmedkaludi/minimal-blogging-amp-theme#1]
- [x] In single page related post design, needs to be changed (ajeet)

- [x] Social icons in the article, design is pending.

- [x] for the images, we need to use the background-size:cover, to fix the image size bug.

- [x] Make sure the description / version number is correct

- [x] Add Themes Selector Screenshot

**Comment by raju-jeelaga** [comment]
- [ ] Add The notification, that, when any one install the theme, It shows the Notification like, These Theme Require an AMP --- refer https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1421
